name: Issues Ejemplo

on:
  issues:
    types: [opened]

jobs:
  procesa-issue:
    runs-on: ubuntu-lates
    steps: 
      - name: Muestra titulo del issue
        run: echo "El titulo del issue es ${{ github.event.issue.title }}"
